# -------------------------------------------------------------------------------
# Generated by PixieDust code generator
# 
# Licensed under the Apache License, Version 2.0 (the 'License');
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
# http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an 'AS IS' BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# Inherited from maven-artifact https://github.com/hamnis/maven-artifact
# -------------------------------------------------------------------------------

from .display import BollingerBandsHandler
from pixiedust.display.display import *

@PixiedustDisplay()
class BollingerBandsHandlerMeta(DisplayHandlerMeta):
    @addId
    def getMenuInfo(self,entity, dataHandler):
        #TODO Add class checking here
        #clazz = entity.__class__.__name__
        #if clazz == "<<some_class_I_care_about":

        #TODO: Change the categoryId, title, icon and id as needed
        return[{"categoryId": "BollingerBandsHandler", "title": "BollingerBandsHandler Plugin", "icon":"fa-gift", "id":"BollingerBandsHandler"}]
    
    """
    Factory method that creates the displayHandler class capable of visualizing the data
    """
    def newDisplayHandler(self,options,entity):
        return BollingerBandsHandler(options,entity)